CREATE TABLE NewTec.PEDIDOS  ( 
	CODIGO  	INT NOT NULL AUTO_INCREMENT,
	CLIENTE 	VARCHAR(40),
    EMAIL		VARCHAR(80),
	ENDERECO	VARCHAR(100),
	ESTADO  	VARCHAR(10),
    
    CODIGO_STARK_SYSTEMS	INTEGER NOT NULL,
    QTD_REATOR_SOLAR 		INTEGER NOT NULL,
	QTD_REATOR_ARK 			INTEGER NOT NULL,
	TOTAL_REATOR_SOLAR   	REAL NOT NULL,
	TOTAL_REATOR_ARK   		REAL NOT NULL,
    TOTAL_STARK_SYSTEM		REAL,
    
    CODIGO_BR_ROBOTICS		INTEGER NOT NULL,
    QTD_ROBO_DOMESTICO 		INTEGER NOT NULL,
	QTD_ROBO_MEDICO 		INTEGER NOT NULL,
    QTD_ROBO_SEGURANCA 		INTEGER NOT NULL,
	TOTAL_ROBO_DOMESTICO   	REAL NOT NULL,
	TOTAL_ROBO_MEDICO   	REAL NOT NULL,
    TOTAL_ROBO_SEGURANCA   	REAL NOT NULL,
	TOTAL_BR_ROBOTICS   	REAL,
    
    FRETE					REAL,
    
    NUM_TRANSACAO_CARTAO	VARCHAR(100),
    OPERADORA_CARTAO		VARCHAR(10),
    TAXA_CARTAO				REAL,
    
    NUM_NOTA_FISCAL			INTEGER,
    
    TOTAL					REAL,
	PRIMARY KEY(CODIGO)
)